matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
before_install:
- sudo apt-get update  
- sudo apt-get install liblapack3 liblapacke liblapacke-dev -y  
- sudo apt-get install libopenblas-base libopenblas-dev -y
- git clone https://github.com/IBM-Swift/Package-Builder.git
script:
- ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR