matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required  
  - os: osx
    osx_image: xcode8
    sudo: required
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
    sudo apt-get update;      
    sudo apt-get install liblapack3 liblapacke liblapacke-dev -y;  
    sudo apt-get install libopenblas-base libopenblas-dev -y;    
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
    brew update;
    brew install homebrew/dupes/lapack;
    brew install homebrew/science/openblas;
  fi  
- git clone https://github.com/IBM-Swift/Package-Builder.git
- ls /usr/local/opt/openblas
- ls /usr/local/opt/lapack
- ls /usr/local/opt/openblas/lib
- ls /usr/local/opt/lapack/lib
script:
- ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR